ci

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,19 +12,131 @@ on:
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  build:
-    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
+  macos-build:
+    name: Swift ${{ matrix.xcode }} on ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest]
-        swift: ["6.0.2", "6.1.0"]
+        os:
+          - macos-14
+          - macos-15
+          - macos-latest
+        xcode:
+          - Xcode_15.2
+          - Xcode_16
+          - Xcode_16.3
+          - Xcode
+        exclude:
+          - os: macos-14
+            xcode: Xcode_16
+          - os: macos-14
+            xcode: Xcode_16.3
+          - os: macos-14
+            xcode: Xcode
+          - os: macos-15
+            xcode: Xcode_15.2
+          - os: macos-15
+            xcode: Xcode
+          - os: macos-latest
+            xcode: Xcode_15.2
+          - os: macos-latest
+            xcode: Xcode_16
+          - os: macos-latest
+            xcode: Xcode_16.3
     runs-on: ${{ matrix.os }}
     steps:
-      - uses: swift-actions/setup-swift@main
-        with:
-          swift-version: ${{ matrix.swift }}
-      - uses: actions/checkout@v5
+      - name: Select Xcode
+        run: echo "DEVELOPER_DIR=/Applications/${{ matrix.xcode }}.app" >> $GITHUB_ENV
+      - name: Checkout repository
+        uses: actions/checkout@v5
+      - name: Swift version
+        run: swift --version
       - name: Build
         run: swift build
       - name: Run tests
         run: swift test --filter AlibabaCloudOSSUnitTests.* --filter AlibabaCloudOSSExtensionUnitTests.*
+        
+  linux-build:
+    name: Swift ${{ matrix.swift_version }} on ${{ matrix.os_version }}
+    runs-on: ${{ matrix.os_version }}
+    strategy:
+      matrix:
+        os_version:
+          - ubuntu-latest
+        swift_version:
+          - "6.0"
+          - "6.1"
+          - nightly
+    container:
+      image: ${{ (contains(matrix.swift_version, 'nightly') && 'swiftlang/swift') || 'swift' }}:${{ matrix.swift_version }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+      - name: Swift version
+        run: swift --version
+      - name: Build
+        run: swift build
+      - name: Run tests
+        run: swift test --filter AlibabaCloudOSSUnitTests.* --filter AlibabaCloudOSSExtensionUnitTests.*
+
+  windows-build:
+    name: Swift ${{ matrix.swift_version }} on ${{ matrix.os_version }}
+    runs-on: ${{ matrix.os_version }}
+    strategy:
+      matrix:
+        os_version:
+          - windows-2022
+        swift_version:
+          - "6.1"
+          - nightly
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+      - name: Install Visual Studio Build Tools
+        run: |
+          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/install-vsb.ps1 -OutFile $env:TEMP\install-vsb.ps1
+          . $env:TEMP\install-vsb.ps1
+          del $env:TEMP\install-vsb.ps1
+      - name: Install Swift
+        run: |
+          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/swift/install-swift.ps1 -OutFile $env:TEMP\install-swift.ps1
+          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/swift/install-swift-${{ matrix.swift_version }}.ps1 -OutFile $env:TEMP\install-swift-${{ matrix.swift_version }}.ps1
+          . $env:TEMP\install-swift-${{ matrix.swift_version }}.ps1
+          del $env:TEMP\install-swift*.ps1
+      - name: Create test script
+        run: |
+          mkdir $env:TEMP\test-script
+          echo @'
+          Set-PSDebug -Trace 1
+          $Source = $env:GITHUB_WORKSPACE
+
+          # Run the command following `Invoke-Program`.
+          # If that command returns a non-zero exit code, return the same exit code from this script.
+          function Invoke-Program($Executable) {
+            & $Executable @args
+            if ($LastExitCode -ne 0) {
+              exit $LastExitCode
+            }
+          }
+          Invoke-Program swift --version
+          Invoke-Program swift test --version
+          Invoke-Program cd $Source
+          '@ >> $env:TEMP\test-script\run.ps1
+
+          if ("${{ inputs.enable_cross_pr_testing && github.event_name == 'pull_request' }}" -eq "true") {
+            echo @'
+          Invoke-WebRequest https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/cross-pr-checkout.swift -OutFile $env:TEMP\cross-pr-checkout.swift
+          # Running in script mode fails on Windows (https://github.com/swiftlang/swift/issues/77263), compile and run the script.
+          Invoke-Program swiftc -sdk $env:SDKROOT $env:TEMP\cross-pr-checkout.swift -o $env:TEMP\cross-pr-checkout.exe
+          Invoke-Program $env:TEMP\cross-pr-checkout.exe "${{ github.repository }}" "${{ github.event.number }}"
+          '@ >> $env:TEMP\test-script\run.ps1
+          }
+
+          echo @'
+          swift build
+          swift test --filter AlibabaCloudOSSUnitTests.* --filter AlibabaCloudOSSExtensionUnitTests.*
+          '@ >> $env:TEMP\test-script\run.ps1
+      - name: Build / tests
+        run: |
+          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
+          RefreshEnv
+          powershell.exe -NoLogo -File $env:TEMP\test-script\run.ps1; exit $LastExitCode
